import { useCallback, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { readChats } from "@/lib/chat-storage";
import { modelById } from "@/lib/ai-models";
import type { ChatSession } from "@/shared/models";
const rtl = { writingDirection: "rtl" as const, textAlign: "right" as const };
export default function ChatsScreen() { const colors = useColors(); const [items, setItems] = useState<ChatSession[]>([]); useFocusEffect(useCallback(() => { void readChats().then(setItems); }, [])); return <ScreenContainer className="px-4" edges={["top", "left", "right"]}><View style={styles.header}><Text style={[styles.kicker, { color: colors.muted }, rtl]}>تاریخچه نشست‌ها</Text><Text style={[styles.title, { color: colors.foreground }, rtl]}>چت‌ها</Text></View>{items.length === 0 ? <View style={styles.empty}><IconSymbol name="message.fill" size={42} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }, rtl]}>هنوز چتی ساخته نشده</Text><Text style={[styles.emptyText, { color: colors.muted }, rtl]}>وقتی یک مدل را در ترمینال اجرا کنید، نشست اینجا ذخیره می‌شود.</Text></View> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const model = modelById(item.modelId); return <Pressable onPress={() => router.push({ pathname: "/model/[id]" as never, params: { id: item.modelId, session: item.id } } as never)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: model.color }]}><Text style={styles.letter}>{model.name.slice(0, 1)}</Text></View><View style={styles.body}><Text style={[styles.name, { color: colors.foreground }, rtl]}>{item.modelName}</Text><Text style={[styles.preview, { color: colors.muted }, rtl]} numberOfLines={1}>{item.lines[item.lines.length - 1]?.text ?? "نشست جدید"}</Text></View><IconSymbol name="chevron.left" size={18} color={colors.muted} /></Pressable>; }} />}</ScreenContainer>; }
const styles = StyleSheet.create({ header: { alignItems: "flex-end", paddingTop: 15, paddingBottom: 18 }, kicker: { fontSize: 11 }, title: { fontSize: 27, fontWeight: "900", marginTop: 3 }, list: { gap: 10, paddingBottom: 28 }, card: { minHeight: 78, borderRadius: 16, borderWidth: 1, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, icon: { width: 44, height: 44, borderRadius: 13, alignItems: "center", justifyContent: "center" }, letter: { color: "#fff", fontSize: 21, fontWeight: "900" }, body: { flex: 1 }, name: { fontSize: 14, fontWeight: "800" }, preview: { fontSize: 10, marginTop: 5 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30, gap: 10 }, emptyTitle: { fontSize: 19, fontWeight: "800" }, emptyText: { fontSize: 13, lineHeight: 22, textAlign: "center" }, pressed: { opacity: 0.72 } });
