import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { AI_MODELS } from "@/lib/ai-models";
const rtl = { writingDirection: "rtl" as const, textAlign: "right" as const };
const statusText = { ready: "Ready", "needs-login": "Login required", experimental: "Experimental" };
export default function ModelsScreen() { const colors = useColors(); return <ScreenContainer className="px-4" edges={["top", "left", "right"]}><View style={styles.header}><View style={styles.brand}><View style={[styles.logo, { backgroundColor: colors.primary }]}><IconSymbol name="terminal" size={22} color="#fff" /></View><View><Text style={[styles.eyebrow, { color: colors.muted }, rtl]}>محیط اجرای کدنویسی</Text><Text style={[styles.title, { color: colors.foreground }, rtl]}>مدل‌های AI</Text></View></View><View style={styles.rgb}><View style={[styles.rgbDot, { backgroundColor: colors.primary }]} /><View style={[styles.rgbDot, { backgroundColor: colors.success }]} /><View style={[styles.rgbDot, { backgroundColor: colors.error }]} /></View></View><Text style={[styles.subtitle, { color: colors.muted }, rtl]}>مدل را انتخاب کنید تا ترمینال اختصاصی و راهنمای فعال‌سازی آن باز شود.</Text><FlatList data={AI_MODELS} numColumns={2} keyExtractor={(item) => item.id} columnWrapperStyle={styles.row} contentContainerStyle={styles.grid} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.aiIcon, { backgroundColor: item.color }]}><Text style={styles.aiLetter}>{item.name.slice(0, 1)}</Text></View><Text style={[styles.modelName, { color: colors.foreground }, rtl]} numberOfLines={1}>{item.name}</Text><Text style={[styles.vendor, { color: colors.muted }, rtl]}>{item.vendor}</Text><View style={styles.status}><View style={[styles.dot, { backgroundColor: item.status === "needs-login" ? colors.warning : item.status === "experimental" ? colors.error : colors.success }]} /><Text style={[styles.statusText, { color: colors.muted }]}>{statusText[item.status]}</Text></View><Pressable onPress={() => router.push({ pathname: "/model/[id]" as never, params: { id: item.id } } as never)} style={({ pressed }) => [styles.enter, { backgroundColor: item.color }, pressed && styles.pressed]}><Text style={styles.enterText}>ورود به مدل</Text><IconSymbol name="chevron.left" size={15} color="#fff" /></Pressable></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", paddingTop: 14, paddingBottom: 9 }, brand: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, logo: { width: 44, height: 44, borderRadius: 14, justifyContent: "center", alignItems: "center" }, eyebrow: { fontSize: 11 }, title: { fontSize: 24, fontWeight: "900", marginTop: 2 }, rgb: { flexDirection: "row", gap: 4 }, rgbDot: { width: 8, height: 8, borderRadius: 4 }, subtitle: { fontSize: 13, lineHeight: 21, textAlign: "right", marginBottom: 10 }, grid: { paddingBottom: 28, gap: 10 }, row: { gap: 10 }, card: { flex: 1, minHeight: 212, borderRadius: 18, borderWidth: 1, padding: 12, alignItems: "flex-end", marginBottom: 10 }, aiIcon: { width: 48, height: 48, borderRadius: 15, alignItems: "center", justifyContent: "center", alignSelf: "flex-end", marginBottom: 10 }, aiLetter: { color: "#fff", fontSize: 24, fontWeight: "900" }, modelName: { fontSize: 14, fontWeight: "800", width: "100%" }, vendor: { fontSize: 10, width: "100%", marginTop: 3 }, status: { flexDirection: "row-reverse", gap: 5, alignItems: "center", width: "100%", marginTop: 9 }, dot: { width: 7, height: 7, borderRadius: 4 }, statusText: { fontSize: 9 }, enter: { width: "100%", height: 36, borderRadius: 10, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 3, marginTop: "auto" }, enterText: { color: "#fff", fontSize: 11, fontWeight: "800" }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
